version: "3"
services:
    mysql:
      image: mysql:5.7
      container_name: ${COMPOSE_PROJECT_NAME}-mysql
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - outside


    webserver:
      image: nginx
      container_name: ${COMPOSE_PROJECT_NAME}-webserver
      working_dir: /www
      volumes:
          - ../../../www:/www
          - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
      restart: always
      links:
        - php-fpm
      networks:
        - outside
      environment:
        - VIRTUAL_HOST=${VIRTUAL_HOST}
        - LETSENCRYPT_HOST=${VIRTUAL_HOST}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      command: /bin/bash -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


    php-fpm:
      build: php-fpm
      container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
      working_dir: /www
      restart: always
      volumes:
        - ../../../www:/www
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      links:
        - mysql
      networks:
        - outside


    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
      environment:
        - VIRTUAL_HOST=pma.${VIRTUAL_HOST}
        - LETSENCRYPT_HOST=pma.${VIRTUAL_HOST}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        - PMA_HOST=mysql
      restart: always
      volumes:
        - /sessions
      links:
        - mysql
      networks:
        - outside


    gulp:
      image: node
      working_dir: /www
      container_name: ${COMPOSE_PROJECT_NAME}-node
      volumes:
        - ../../../www:/www
      command: bash -c "npm install && npm install -g gulp && gulp"


networks:
  outside:
    external:
      name: ${DOCKER_NETWORK}
